# Generated by Django 3.2.5 on 2021-07-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('street_address', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('zip_code', models.CharField(max_length=12)),
            ],
        ),
    ]
